### ISSUE TITLE
Infinite loading

### ISSUE THREAD

**Issue by CAProductions** [MeechaPooch/Blocklive#3]
whenever I press "blocklive share", the bar spins indefinitely, reload doesn't fix either.

**Comment by Minemaster552** [comment]
Same, i wonder if the issues being worked on? Hopefully.

**Comment by MeechaPooch** [comment]
this can mean a lot of things but in this case it was because the server went down and the ip changed (two separate issues). Im waiting for google to publish the new version with a dns name instead of a raw ip address. Try again in 2 days, it should all be fixed by then.

**Comment by CAProductions** [comment]
thanks for fixing! works now
