### ISSUE TITLE
Can't find it.

### ISSUE THREAD

**Issue by Pikminyo83** [MeechaPooch/Blocklive#5]
If I search it up, I get an advertisement account, with a project showing how to get it. I see the github, and I can't find the extension on the Chrome Extension Store. Is there another way to get it or..?

**Comment by CST1229** [comment]
The extension was temporarily taken down from CWS by the creator due to API (idk if scratch or blocklive) changes that might break it AFAIK.

**Comment by MeechaPooch** [comment]
Blocklive is back on the chrome web store! https://chrome.google.com/webstore/detail/blocklive-scratch-realtim/gelkmljpoacdjkjkcfekkmgkpnmeomlk
